In [1]:
import numpy as np 

In [5]:
# what is an array 

a =np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [10]:
a2 = a[np.newaxis,np.newaxis,:]
print(a2)

[[[0 1 2 3 4 5]]]


In [11]:
a2.shape

(1, 1, 6)

# creating array with numpy


In [16]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6),(7,8,9,1,2,3)])
a.shape
b.shape


(2, 6)

In [17]:
b

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

# initialize arrays

In [20]:
zeros = np.zeros((3,4)) # rowa,columns 
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
ones = np.ones((5,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Full with desired values 
full = np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [26]:
# Creating the identity matrix
identity = np.eye(5)  
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Checking the data type
identity.dtype

dtype('float64')

In [28]:
# N demensional array 
type(identity)

numpy.ndarray

In [29]:
# array attribues 
b.shape

(2, 6)

In [32]:
a.ndim
# for checking the dimensional

1

In [31]:
len(a)
# Give the number of elements present iin array 


6

#  Basic operation

In [3]:
# Taking the subtraction
g  = a- b
g

NameError: name 'a' is not defined

In [37]:
#  Taking the addition
h1 = np.add(a , b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 8, 10, 12,  5,  7,  9]])

In [39]:
# taking square 
k = a**2
k

array([ 1,  4,  9, 16, 25, 36])

In [40]:
# Taking the division
s = a / b 
s

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.14285714, 0.25      , 0.33333333, 4.        , 2.5       ,
        2.        ]])