# Numpy(Part2)

In [3]:
import numpy as np 


In [4]:
empty  = np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
x = np.arange(6)

x


array([0, 1, 2, 3, 4, 5])

In [6]:
# Array of even Number
even = np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [7]:
# Array of off nummber
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [8]:
# Specific difference kai sath 
diff = np.arange(0,23,3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [9]:
# Follow the same trend in the line 
line = np.linspace(0,20,num=5, dtype=np.int64)
line

array([ 0,  5, 10, 15, 20], dtype=int64)

In [10]:
line.dtype

dtype('int64')

In [11]:
# define the data type of array 
x = np.arange(0, 50,2,dtype=np.float32)
x
# INternal values does not the  change 

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48.],
      dtype=float32)

In [12]:
# Sorting the array 
arr =np.sort(x)
arr

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48.],
      dtype=float32)

In [13]:
a = np.array([1,2,3,3,4,5,5])
b = np.array([6,7,8,9,97,6])
c =np.concatenate((a, b))
c

array([ 1,  2,  3,  3,  4,  5,  5,  6,  7,  8,  9, 97,  6])

# Concatnate the 2D Array

In [14]:
x = np.array([[1,2],[3,4]])
y =  np.array([[6,7]])

In [15]:
z =np.concatenate((x,y), axis=0)
z

array([[1, 2],
       [3, 4],
       [6, 7]])

In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9]])

In [20]:
z =np.concatenate((x,y), axis= 1)
z

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [21]:
x.ndim

2

#   Three Dimensional Array 

In [24]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [28]:
len(array_example)
array_example.size
array_example.dtype
array_example.shape

(3, 2, 4)

In [29]:
# create the 3d array (3,1,4)
array_3d = np.zeros((3, 1, 4))
array_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

# indexing and Slicing 

In [33]:
a = np.array([1,2,3,44,5,56,6,7,])
a

array([ 1,  2,  3, 44,  5, 56,  6,  7])

In [37]:
a[2:5]
a[-4:]
a[-4:-2]

array([ 5, 56])

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [41]:
a[0]
a[1:,1:]
a[2:3]

array([[ 9, 10, 11, 12]])

In [42]:
b[b % 2 == 0]
# Tell those numbewr are ramaining zero after the division by 2 

array([6, 8, 6])

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Use three condition to filter the array
# 1. OR 
# 2. AND 
# 3. Not


In [ ]:
a[(a > 2) & (a< 11) ]
a[(a > 2) | (a< 11) ]
a[(a > 2) ! (a< 11) ] # Focus on the sign 