# Numpy indexing and slicing 

In [2]:
import numpy as np 

In [3]:
# create the array 
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[-2]

8

In [10]:
b=np.arange(0,20,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
b[1:16]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
c = b.reshape(2,5)
c


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [16]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr1 = a[3:8]
arr1


array([4, 5, 6, 7, 8])

In [18]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

# Vercitally arrange

In [19]:

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

# Horizaontally Arrange 

In [20]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# REshape the matrix 

In [21]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Split the matrix into three equally parts 

In [22]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

## Into third and forth parts 

In [23]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

# Creating the matrix

## You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [30]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
# create the matrix of big dimension 
a = np .arange(0,100,2)
a


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [36]:
a = a.reshape(5,10)
a


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

### Slicing matrix

In [38]:
a[1:3 , 3:5]

array([[26, 28],
       [46, 48]])

In [44]:
a[0:3,3:6] # First define the rows and later on tell the columns 

array([[ 6,  8, 10],
       [26, 28, 30],
       [46, 48, 50]])

In [47]:
a.max()
a.min()
a.sum()

2450

In [48]:
# tell which array we find the min or max value by usung the axis in codd
a.max(axis=0) # Only for column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [49]:
a.max(axis=1) # only for rows

array([18, 38, 58, 78, 98])

In [50]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [52]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [54]:
np.ones(3)
np.zeros(3)

array([0., 0., 0.])

In [55]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.7162379 , 0.55620558, 0.1561944 ])

# Reverse the array 


In [57]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [58]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [59]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [60]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


# Reshpaing and flatting multidimensional 

In [61]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])